version: '3'

networks:
  loki:

services:
  loki:
    image: grafana/loki:latest
    ports:
      - 3100:3100
    command: -config.file=/etc/loki/loki.yaml
    restart: unless-stopped
    volumes:
      - ./loki.yaml:/etc/loki/loki.yaml
      - /mnt/Dockershare/Docker_Loki:/loki
    networks:
      - loki

  alloy:
    image: grafana/alloy:latest
    ports:
      - 12345:12345
#   environment:
#     CONFIG_FILE_PATH: /etc/alloy/config.alloy
    volumes:
      - ./config.alloy:/etc/alloy/config.alloy
      - /mnt/Dockershare/Docker_Loki:/loki
    command: run --server.http.listen-addr=0.0.0.0:12345 /etc/alloy/config.alloy
    restart: unless-stopped
    networks:
      - loki

